import { BlockedResourceTypes, SkippedResources } from "../interfaces";

export const blockedResourceTypes: BlockedResourceTypes = [
    "image",
    "media",
    "stylesheet",
    "font",
    "texttrack",
    "object",
    "beacon",
    "csp_report",
    "imageset",
  ];
  
export const skippedResources: SkippedResources = [
    "quantserve",
    "adzerk",
    "doubleclick",
    "adition",
    "exelator",
    "sharethrough",
    "fullstory",
    "cdn.api.twitter",
    "analytics.twitter.com",
    "static.ads-twitter.com",
    "google-analytics",
    "googletagmanager",
    "google",
    "fontawesome",
    "facebook",
    "analytics",
    "optimizely",
    "clicktale",
    "mixpanel",
    "zedo",
    "clicksor",
    "tiqcdn",
    "b9zcrrrvom",
    "cloudflare",
    "cdn-cgi",
    "chunks",
    "commons",
    "webpack",
    "runtime",
    "_next/static/",
    "tmall",
    "retcode",
    "mpulse.net",
    "alilog",
    "cobra",
    "setCommonCookie",
    "lighthouse",
    "lighthouse.config",
    "messageUnreadCountAjaxService",
    "header-ui",
    "vendors.js",
    "home.js",
    "alicdn",
    "standalone",
  ];
  